services:
  backend:
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      INIT_IMPORT_FRONTEND_TRANSLATIONS: ${INIT_IMPORT_FRONTEND_TRANSLATIONS:-0}
      FRONTEND_LOCALES_DIR: ${FRONTEND_LOCALES_DIR:-/tmp/locales}
      FRONTEND_SOURCE_LANG: ${FRONTEND_SOURCE_LANG:-cs}
      INIT_IMPORT_OVERWRITE: ${INIT_IMPORT_OVERWRITE:-1}
      INIT_IMPORT_ONLY_IF_EMPTY: ${INIT_IMPORT_ONLY_IF_EMPTY:-1}

  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
