# Generated by Django 4.2.29 on 2026-03-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_system', '0004_page_i18n_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IframeEmbed',
        ),
        migrations.DeleteModel(
            name='InfoBox',
        ),
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
