# Generated by Django 4.2.29 on 2026-03-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_system', '0005_delete_iframeembed_delete_infobox_delete_mediafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_i18n', models.JSONField(blank=True, default=dict)),
                ('content_json', models.JSONField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
