# Generated by Django 5.2.9 on 2026-03-25 10:00

import editorial_system.photo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial_system", "0006_infobox"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("image", models.FileField(upload_to=editorial_system.photo.models.photo_upload_to)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["id"]},
        ),
    ]
