# Generated by Django 5.2.9 on 2026-08-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_system', '0010_photoplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='alt_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
