# Generated by Django 5.2.9 on 2026-08-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_system', '0011_photo_alt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infobox',
            name='title',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='alt_text',
        ),
        migrations.AddField(
            model_name='photo',
            name='alt_text_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
