# Generated by Django 5.2.9 on 2026-08-10 08:08

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_system', '0012_consolidate_i18n_text_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.functions.text.Lower('category'), name='photo_category_lower_idx'),
        ),
    ]
