# Generated by Django 5.2.17 on 2026-08-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_system', '0013_alter_photo_category_photo_photo_category_lower_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infobox',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Moment the info box stops being visible. For a single-day info box, set this to the end of that day (e.g. 23:59), not the same time as the start - otherwise it will never be visible.', null=True),
        ),
        migrations.AlterField(
            model_name='infobox',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Moment the info box becomes visible.', null=True),
        ),
    ]
