# Generated by Django 4.2.27 on 2025-12-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='items',
            field=models.ManyToManyField(to='pension.reservationitem'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='items',
            field=models.ManyToManyField(to='pension.reservationitem'),
        ),
    ]
