# Generated by Django 4.2.28 on 2026-02-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0002_alter_package_items_alter_reservation_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='primary_guest',
            field=models.ForeignKey(help_text='The primary guest who will receive the reservation', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='pension.guest'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
