# Generated by Django 4.2.28 on 2026-02-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0003_room_price_alter_reservation_primary_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='max_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
