# Generated by Django 4.2.28 on 2026-02-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0004_room_max_adults_room_max_children_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='room',
            name='price_for_adult',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='price_for_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
