# Generated by Django 4.2.28 on 2026-02-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0005_remove_room_capacity_remove_room_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
