# Generated by Django 4.2.28 on 2026-02-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0006_room_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='items',
        ),
        migrations.DeleteModel(
            name='ReservationItem',
        ),
    ]
