# Generated by Django 4.2.28 on 2026-02-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0007_remove_reservation_items_delete_reservationitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.AddField(
            model_name='reservation',
            name='rooms',
            field=models.ManyToManyField(blank=True, null=True, related_name='reservations', to='pension.room'),
        ),
    ]
