# Generated by Django 4.2.28 on 2026-02-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0008_remove_reservation_room_reservation_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='city',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='document_number',
        ),
    ]
