# Generated by Django 4.2.28 on 2026-02-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0009_remove_guest_address_remove_guest_city_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('first_name', 'last_name', 'email')},
        ),
    ]
