# Generated by Django 4.2.28 on 2026-02-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0010_alter_guest_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='check_reservation_dates',
        ),
    ]
