# Generated by Django 4.2.29 on 2026-03-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0013_room_i18n_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='pension.room'),
        ),
    ]
