# Generated by Django 5.2.17 on 2026-08-10 16:34

import django.db.models.deletion
from django.db import migrations, models


def create_default_voucher_amounts(apps, schema_editor):
    VoucherAmount = apps.get_model('pension', 'VoucherAmount')
    for sort_order, value in enumerate([500, 1000, 1500, 2000]):
        VoucherAmount.objects.create(value=value, currency='CZK', sort_order=sort_order)


def remove_default_voucher_amounts(apps, schema_editor):
    VoucherAmount = apps.get_model('pension', 'VoucherAmount')
    VoucherAmount.objects.filter(value__in=[500, 1000, 1500, 2000], currency='CZK').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0016_add_db_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='CZK', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='VoucherOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='CZK', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('is_sent', models.BooleanField(default=False, help_text='Check off once the voucher has been sent to the customer.')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(help_text='The guest who ordered the voucher', on_delete=django.db.models.deletion.PROTECT, related_name='voucher_orders', to='pension.guest')),
            ],
        ),
        migrations.RunPython(create_default_voucher_amounts, remove_default_voucher_amounts),
    ]
