# Generated by Django 5.2.9 on 2026-08-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0017_voucheramount_voucherorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
