# Generated by Django 5.2.9 on 2026-08-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0021_seed_amenity_icons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='max_adults',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_children',
        ),
    ]
