# Generated by Django 5.2.17 on 2026-08-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0023_appsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherorder',
            name='delivery_method',
            field=models.CharField(choices=[('email', 'E-mail'), ('print', 'Tištěná podoba')], default='email', help_text='Whether the voucher should be sent by email or in printed form.', max_length=10),
        ),
    ]
