# Generated by Django 5.2.17 on 2026-08-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0024_voucherorder_delivery_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('link', models.URLField(help_text='Odkaz na dané místo (web, Google Maps apod.).')),
                ('media_type', models.CharField(choices=[('image', 'Obrázek'), ('iframe', 'Iframe')], default='image', max_length=10)),
                ('media_url', models.URLField(help_text='Adresa obrázku, nebo URL pro vložení do iframe.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
