# Generated by Django 5.2.9 on 2026-09-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0027_voucheramount_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyplace',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='media_url',
            field=models.URLField(blank=True, help_text="URL pro vložení do iframe (jen media_type='iframe'). Pro media_type='image' se ignoruje – obrázek se řeší přes photo placement systém (location=f'nearby-place-{id}')."),
        ),
    ]
