# Generated by Django 5.2.9 on 2026-09-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0028_nearbyplace_name_i18n_alter_nearbyplace_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyplace',
            name='link',
            field=models.URLField(help_text='Odkaz na dané místo (web, Google Maps apod.).', max_length=2000),
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='media_url',
            field=models.URLField(blank=True, help_text="URL pro vložení do iframe (jen media_type='iframe'). Pro media_type='image' se ignoruje – obrázek se řeší přes photo placement systém (location=f'nearby-place-{id}').", max_length=2000),
        ),
    ]
